### ISSUE TITLE
Columns not nicely aligned as they should be in Markdown

### ISSUE THREAD

**Issue by mudrd8mz** [LafColITS/moodle-dataformat_markdown#1]
One of the essential features of the Markdown format (and the key reason why it actually exists) is that the source code itself should look nice and readable for humans. That was why Markdown was introduced as an alternative to HTML.

Currently the plugin exports table in machine readable format like

![image](https://cloud.githubusercontent.com/assets/85831/16296767/12371138-392e-11e6-8adc-222880b51e12.png)

which effectively makes no difference from CSV format.

I was expecting this plugin would produce nicely formatted tables such as those described in the markdown cheatsheet where column borders are nicely aligned. Something like:

![image](https://cloud.githubusercontent.com/assets/85831/16296918/a36a881a-392e-11e6-9f65-792a1a360b40.png)

I understand it can be tricky, of maybe not even fully possible, to align columns by the longest value length (as it is difficult in streaming). But at least checking the first few hundreds records and setting border by them could help in most cases. Or a fixed length or something would be really nice.

**Comment by mudrd8mz** [comment]
I have not looked at details but it seems to me you could have a buffer for the first N records and start writing the output later when you have enough records to estimate the columns width (or when `write_footer()` is called, whichever comes first).

**Comment by mackensen** [comment]
Thanks @mudrd8mz for the excellent suggestion. I've always used a Markdown reader so I didn't consider this use case.

It's tricky as there's no access to data beforehand. I solved this tentatively by processing and storing the first 100 rows, then flushing that data and proceeding normally. Seems to work okay, and you get pretty output.
